import React from 'react';
import ReactDOM from 'react-dom';
import CounterWithCustomHook from './components/01-useState/CounterWithCustomHook';
import { SimpleForm } from './components/02-useEffect/SimpleForm';
import { FormWithCustomHooks } from './components/02-useEffect/FormWithCustomHooks';
import { MultipleCustomHook } from './components/03-examples/MultipleCustomHook';
import { FocusScreen } from './components/04-useRef/FocusScreen';
import { RealExampleRef } from './components/04-useRef/RealExampleRef';
import { Layout } from './components/05-useLayoutEffect/Layout';
import { Memorize } from './components/06-memos/Memorize';
import { MemoHook } from './components/06-memos/MemoHook';
import { CallbackHook } from './components/06-memos/CallbackHook';
// import HookApp from './HookApp';
// import CounterApp from './components/01-useState/CounterApp';
ReactDOM.render(<CallbackHook />, document.getElementById('root'));
